"""Add location column to Restaurant model

Revision ID: bd198975be2d
Revises: 254a760373f9
Create Date: 2024-06-29 22:28:09.179271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd198975be2d'
down_revision = '254a760373f9'
branch_labels = None
depends_on = None


def upgrade():
    # Drop any existing temporary tables if needed
    op.drop_table('_alembic_tmp_pizzas')
    
    # Alter columns in the 'pizzas' table
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.String(length=255),
                              existing_nullable=False)
        batch_op.alter_column('ingredients',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=255),
                              existing_nullable=False)

    # Alter columns in the 'restaurant_pizzas' table
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.alter_column('pizza_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('restaurant_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    # Add the 'location' column to the 'restaurants' table with a default value
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False, server_default='Unknown'))
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.String(length=255),
                              existing_nullable=False)
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('location')

    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.alter_column('restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('pizza_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.create_table('_alembic_tmp_pizzas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ingredients', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
